name: ci/cd deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Deploy-Job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3 # 공간 설정
        with: 
          submodules: true
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build --exclude-task test
        # 이전 빌드의 출력물 삭제, 프로젝트 컴파일 필요한 아티팩트 생성, 태스크 실행 태스크 제외

      - name: Login docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: List directory contents
        run: |
          pwd
          ls -la
          cd build/libs
          ls -la

      - name: Docker Image Build
        run: docker build -t {{ secrets.IMAGE_USERNAME }}/${{ secrets.PROJECT_NAME }} ./

      - name: Docker Image Push
        run: docker push {{ secrets.IMAGE_USERNAME }}/${{ secrets.PROJECT_NAME }}
      
      - name: List directory contents
        run: |
          pwd
          ls -la
          cd build/libs
          ls -la

      - name: Application Run
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo docker kill ${{ secrets.PROJECT_NAME }}
            sudo docker rm -f ${{ secrets.PROJECT_NAME }}
            sudo docker rmi ${{ secrets.IMAGE_USERNAME }}/${{ secrets.PROJECT_NAME }}
            sudo docker pull ${{ secrets.IMAGE_USERNAME }}/${{ secrets.PROJECT_NAME }}
  
            sudo docker run -p "8080":"80" \
            --name ${{ secrets.PROJECT_NAME }} \
            -d ${{ secrets.IMAGE_USERNAME }}/${{ secrets.PROJECT_NAME }}
